### ISSUE TITLE
Sun/stars check didn't reset the compass heading

### ISSUE THREAD

**Issue by pdurdin** [badgib/ASimpleCompass#2]
None of the following worked (last should set the ?, really):

Gazing up at the stars, you determine that the ship is heading turnwise-hubwards.
Squinting at the sun, you determine that the ship is heading hubwards.
Squinting at the sun, you determine that the ship is heading adsfdsdfsdf.

I tried to debug it, as far as I could tell the regexp wasn't working and HandleDirection never fired.

**Comment by badgib** [comment]
ohh, right, thanks! i'm on it!

**Comment by badgib** [comment]
fix pushed
closing issue
